[Variables]

; It's recommened you use any text editor other than Notepad.
; eg. VS Code, NeoVim, Notepad++

; ---------------------------------------- ;

; ███████ ███████ ████████ ████████ ██ ███    ██  ██████  ███████ 
; ██      ██         ██       ██    ██ ████   ██ ██       ██      
; ███████ █████      ██       ██    ██ ██ ██  ██ ██   ███ ███████ 
;      ██ ██         ██       ██    ██ ██  ██ ██ ██    ██      ██ 
; ███████ ███████    ██       ██    ██ ██   ████  ██████  ███████

; ---------------------------------------- ;

Scale=1

; ---------------------------------------- ;

; Enables round corners for the shapes.
UseRoundCorner=1
;
Use24HFormat=0

; ---------------------------------------- ;

Color.Background=0,0,0
Color.Highlight=255,255,255

Color.Text=0,0,0
Color.SubText=0,0,0,(255/1.5)

; ---------------------------------------- ;

; ██     ██ ███████  █████  ████████ ██   ██ ███████ ██████  
; ██     ██ ██      ██   ██    ██    ██   ██ ██      ██   ██ 
; ██  █  ██ █████   ███████    ██    ███████ █████   ██████  
; ██ ███ ██ ██      ██   ██    ██    ██   ██ ██      ██   ██ 
;  ███ ███  ███████ ██   ██    ██    ██   ██ ███████ ██   ██

; ---------------------------------------- ;

; This text will be used only on the "The Weather in ******* is" sentence, this will 
; not affect to weather searchs.
Weather.City=*******

; Set your location using coordinates.
Weather.Latitude=40.7127281
Weather.Longitude=-74.0060152

; Unit system to use when reporting temperature ; Farenheit or Celcius ; F | C
Weather.Units=C

; Language to use when reporting conditions like cloudy, rain, snow etc.
Weather.Language=en-US

; ---------------------------------------- ;

; ██████  ██       █████  ██    ██ ███████ ██████  
; ██   ██ ██      ██   ██  ██  ██  ██      ██   ██ 
; ██████  ██      ███████   ████   █████   ██████  
; ██      ██      ██   ██    ██    ██      ██   ██ 
; ██      ███████ ██   ██    ██    ███████ ██   ██

; ---------------------------------------- ;

; Text that will be used when no listen music.
Player.IdleText=%USERNAME%
